name: jaxkern
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
# Standard Libraries
- numpy>=1.19
- scipy>=1.5
- scikit-learn>=0.23
- matplotlib>=3.3
- seaborn>=0.11
# Documentation
- conda-forge::nbsphinx
- conda-forge::sphinx
- conda-forge::pandoc
- conda-forge::ipykernel
- conda-forge::ipython
- pip
- pip:
  # Jax framework
  - "git+https://github.com/google/jax.git"
  - jaxlib
  - "git+git://github.com/google/objax.git"
  - "git+git://github.com/deepmind/chex.git"
  - "numpyro"
  - "tfp-nightly"
  # formatting
  - black
  - isort
  - mypy
  - pytest
  - flake8
  - pylint
  - pyprojroot
  # logging
  - wandb
  # documentation
  - sphinx
  - sphinx-tabs
  - sphinx_rtd_theme
  - sphinx-autobuild